Oops

diff --git a/.github/workflows/combine_scalasteward_prs.yml b/.github/workflows/combine_scalasteward_prs.yml
--- a/.github/workflows/combine_scalasteward_prs.yml
+++ b/.github/workflows/combine_scalasteward_prs.yml
@@ -38,8 +38,10 @@ jobs:
             echo "Bringing in: $pr"
             git fetch origin pull/${pr}/head:pr_${pr}
 
-            git rebase pr_${pr} $BRANCH || EXIT_CODE="$?"
-            if [ "${EXIT_CODE}" == "0" ]
+            git rebase pr_${pr} $BRANCH || EXIT_CODE=$?
+
+            # EXIT_CODE is only set if the command failed:
+            if [ "${EXIT_CODE}" == "" ]
             then
               SUCCESSFUL_PRS+=( "$pr" )
             else
